using System;
using System.Collections.Generic;

namespace Match3Lab.Core
{
    public enum CellSpecKind : byte
    {
        /// <summary>Not part of the board.</summary>
        Hole,
        /// <summary>Playable, but starts empty (filled by the first gravity pass).</summary>
        Empty,
        /// <summary>Playable, starts with a random colour that does not form a match.</summary>
        Random,
        /// <summary>Playable, starts with the given colour.</summary>
        FixedColor,
        /// <summary>A box with the given hit points; no piece.</summary>
        Box,
    }

    /// <summary>How one cell starts. Authoring data — the runtime works on <see cref="Cell"/>.</summary>
    public readonly struct CellSpec : IEquatable<CellSpec>
    {
        public readonly CellSpecKind Kind;
        public readonly byte Color;
        public readonly byte BoxHitPoints;
        public readonly byte Ice;
        public readonly byte Grass;

        public CellSpec(CellSpecKind kind, byte color = 0, byte boxHitPoints = 0, byte ice = 0, byte grass = 0)
        {
            Kind = kind;
            Color = color;
            BoxHitPoints = boxHitPoints;
            Ice = ice;
            Grass = grass;
        }

        public static readonly CellSpec Hole = new CellSpec(CellSpecKind.Hole);
        public static readonly CellSpec Random = new CellSpec(CellSpecKind.Random);

        public bool Equals(CellSpec o) =>
            Kind == o.Kind && Color == o.Color && BoxHitPoints == o.BoxHitPoints && Ice == o.Ice && Grass == o.Grass;
        public override bool Equals(object obj) => obj is CellSpec o && Equals(o);
        public override int GetHashCode() => unchecked((((((int)Kind * 31 + Color) * 31 + BoxHitPoints) * 31 + Ice) * 31) + Grass);
    }

    /// <summary>
    /// Everything that defines a level: size, move budget, colour count, goals and the starting
    /// layout. Plain data — no behaviour beyond validation — so it can be authored in the Unity
    /// editor, written to text, generated by code, and shipped to a headless simulator unchanged.
    /// </summary>
    public sealed class LevelDefinition
    {
        public const int MinColors = 3;
        public const int MaxColors = 6;
        public const int MaxSize = 12;

        public string Name = "";
        public int Width;
        public int Height;
        public int Moves;
        public int ColorCount = 5;
        public List<Goal> Goals = new List<Goal>();

        /// <summary>Row-major, top row first; length must be Width * Height.</summary>
        public CellSpec[] Cells = Array.Empty<CellSpec>();

        public CellSpec GetCell(int x, int y) => Cells[y * Width + x];

        /// <summary>The same level with a different move budget. Cells and goals are shared, not copied — treat the result as read-only.</summary>
        public LevelDefinition WithMoves(int moves)
        {
            return new LevelDefinition
            {
                Name = Name,
                Width = Width,
                Height = Height,
                Moves = moves,
                ColorCount = ColorCount,
                Goals = Goals,
                Cells = Cells,
            };
        }

        /// <summary>Human-readable problems with this definition; empty when it is valid.</summary>
        public List<string> Validate()
        {
            var errors = new List<string>();
            if (Width <= 0 || Width > MaxSize) errors.Add("width must be 1.." + MaxSize + ", got " + Width);
            if (Height <= 0 || Height > MaxSize) errors.Add("height must be 1.." + MaxSize + ", got " + Height);
            if (Moves <= 0) errors.Add("moves must be positive, got " + Moves);
            if (ColorCount < MinColors || ColorCount > MaxColors)
                errors.Add("colors must be " + MinColors + ".." + MaxColors + ", got " + ColorCount);
            if (Goals.Count == 0) errors.Add("at least one goal is required");
            if (Width > 0 && Height > 0 && Cells.Length != Width * Height)
                errors.Add("cells length " + Cells.Length + " does not match " + Width + "x" + Height);

            int playable = 0;
            int grass = 0, ice = 0, boxHp = 0;
            for (int i = 0; i < Cells.Length; i++)
            {
                var c = Cells[i];
                if (c.Kind == CellSpecKind.FixedColor && c.Color >= ColorCount)
                    errors.Add("cell " + i + " uses color " + c.Color + " but the level has " + ColorCount + " colors");
                if (c.Kind == CellSpecKind.Box && c.BoxHitPoints == 0)
                    errors.Add("cell " + i + " is a box with 0 hit points");
                if (c.Kind == CellSpecKind.Hole && (c.Ice > 0 || c.Grass > 0))
                    errors.Add("cell " + i + " is a hole but has obstacle layers");
                if ((c.Kind == CellSpecKind.Box || c.Kind == CellSpecKind.Empty) && c.Ice > 0)
                    errors.Add("cell " + i + " has ice but no piece under it");
                if (c.Kind != CellSpecKind.Hole && c.Kind != CellSpecKind.Box) playable++;
                grass += c.Grass;
                ice += c.Ice;
                boxHp += c.BoxHitPoints;
            }
            if (Cells.Length > 0 && playable < 3) errors.Add("fewer than 3 playable cells");

            foreach (var g in Goals)
            {
                switch (g.Kind)
                {
                    case GoalKind.Color when g.Color >= ColorCount:
                        errors.Add("goal targets color " + g.Color + " but the level has " + ColorCount + " colors");
                        break;
                    case GoalKind.Grass when g.Target > grass:
                        errors.Add("goal asks for " + g.Target + " grass but the layout only has " + grass);
                        break;
                    case GoalKind.Ice when g.Target > ice:
                        errors.Add("goal asks for " + g.Target + " ice but the layout only has " + ice);
                        break;
                    case GoalKind.Box when g.Target > boxHp:
                        errors.Add("goal asks for " + g.Target + " box hits but the layout only has " + boxHp);
                        break;
                }
            }
            return errors;
        }

        public bool IsValid => Validate().Count == 0;

        /// <summary>Throws with every problem listed when the definition is not valid.</summary>
        public void EnsureValid()
        {
            var errors = Validate();
            if (errors.Count > 0)
                throw new LevelFormatException("Invalid level '" + Name + "': " + string.Join("; ", errors));
        }
    }

    public sealed class LevelFormatException : Exception
    {
        public int Line { get; }

        public LevelFormatException(string message, int line = 0)
            : base(line > 0 ? "line " + line + ": " + message : message)
        {
            Line = line;
        }
    }
}
